### ISSUE TITLE
Simple Volume Creator should copy container contents into volume

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry/garden-linux#52]
Sometimes a Dockerfile will denote a volume for an existing directory or symlink in the container, the expected behavior is that the Docker runtime will copy those contents into the volume during initialization (e.g. for sharing).

Currently Garden-linux just creates the volume directory inside the container and will fail with a "file exists" when initializing the volume if there are contents already there.

**Comment by goonzoid** [comment]
Hi @svrc-pivotal. Sorry for the slow response.

I'm having a little trouble parsing this, and I don't have time to go and play with Docker to understand the expected behavior right now. Any chance you could provide a concrete example that illustrates what's supposed to happen, and what actually happens?

Thanks!

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#116969637](https://www.pivotaltracker.com/story/show/116969637) Simple Volume Creator should copy container contents into volume


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by svrc-pivotal** [comment]
With runC this probably is moot.
